### PR TITLE
#1505 : use model for datePicker

### PR DESCRIPTION
**Pull request by dominiksteiner**
@albi34 @amirmehmood please review

### CODE REVIEW

**Comment by albi34** [comment]
I'm not sure I understand the purpose of this PR ? 

It seems to be a bit misleading because "model" is a keyword used heavily in Angular, mainly through the ng-model directive which is part of the core modules of Angular and that you see in a lot of inputs in our apps (stuff like <input type="text" ng-model="scope.name"/>). 

So in my mind a model is used to bind a DOM element to a scope value, but here we use "model" directly as the scope value name.

**Comment by dominiksteiner** [comment]
the use case is that we want to be able to show the date picker from within the timelineItemDetail of teamOne. This can be achieved if we use an object that is bound to the action that triggers that visibility so in teamOne where we get passed in the item attribute (that has all it's actions to it, it should be then as simple as changing that value of datePicker.visible to true)

**Comment by amirmehmood** [comment]
lgtm

**Comment by dominiksteiner** [comment]
@albi34 changed from model to config as discussed

**Comment by albi34** [comment]
looks good, thanks

**Pull request merged**
